name: CI

on:
   push: 

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Baixar código
          uses: actions/checkout@v4


        - name: Configurar Python
          uses: actions/setup-python@v5
          with:
           python-version: "3.14"

        - name: Instalar dependências
          run: pip install -r requirements.txt
          
        - name: Executar seletor de testes com IA
          run: python main.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GIT_BEFORE: ${{ github.event.before }}
          GIT_AFTER: ${{ github.sha }}